version: "3.8"

services:
  web:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=mohamedfathy
      - POSTGRES_PASSWORD=MOHmaed621998
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
