# Generated by Django 5.1.3 on 2024-12-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(default='###', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(),
        ),
    ]
