# Generated by Django 5.1.3 on 2024-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0002_profile_phone_number_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='titles',
            field=models.CharField(default='', max_length=255),
        ),
    ]
