name: Docker Build and Push

on:
  push:
    branches:
      - '*'  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Add Windows to the matrix

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set DOCKER_BUILDKIT=0 for Windows runners to disable BuildKit
    - name: Set BuildKit to 0 for Windows
      if: runner.os == 'Windows'
      run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile  # Specify the path to your Dockerfile
        push: true
        tags: mohamedfathyzaky621/test  # Replace with your Docker Hub username and repository name
